version: '3'
services:
  pl:
    image: pcourbin/pl:0.7.1
    environment:
      - PL_ENV_TYPE=release
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=pl
      - DATABASE_PASSWORD=plpassword
      - ALLOWED_HOSTS=*
      - SECRET_KEY=mygreatsupersecretkey
    ports:
      - 8000:8000
    links:
      - pg

  pg:
    image: postgres
    environment:
      - POSTGRES_USER=pl
      - POSTGRES_PASSWORD=plpassword
      - POSTGRES_DB=django_premierlangage
